apiVersion: v1
kind: Pod
metadata:
  name: calculator
spec:
  containers:
  - name: tex-to-pdf-service
    image: eu.gcr.io/sootsafe-app-test/tex-to-pdf-service:0.1
  - name: calculator-service
    image: eu.gcr.io/sootsafe-app-test/sootsafe-backend:0.1
    env:
      - name: PDF_SERVICE_ADDRESS
        value: "localhost"
      - name: PDF_SERVICE_PORT
        value: "50051"
      - name: FIREBASE_KEY_FILE_LOCATION
        value: "/keys/SootSafeAppTest.json"
      - name: FIREBASE_STORAGE_BUCKET
        value: "sootsafe-app.appspot.com"
